apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "misskey.name" . }}-deployment
  labels:
    app: {{ include "misskey.name" . }}
spec:
  replicas: 0
  selector:
    matchLabels:
      app: {{ include "misskey.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "misskey.name" . }}
    spec:
      initContainers: {{ include "misskey.initContainers" . | nindent 8 }}
      containers:
        - name: {{ include "misskey.name" . }}
          image: "{{ .Values.image.index }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["pnpm", "run", "start"]
          ports:
            - containerPort: {{ .Values.port }}
          env:
            - name: NODE_ENV
              value: {{ .Values.environment }}
          volumeMounts:
            - name: {{ include "misskey.name" . }}-configuration-destination
              mountPath: /misskey/.config
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.port }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.port }}
            failureThreshold: 1
            periodSeconds: 1
          startupProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.port }}
            failureThreshold: 60
            periodSeconds: 1
          resources:
            requests:
              memory: "4Gi"
              cpu: "1500m"
            limits:
              memory: "6Gi"
              cpu: "3000m"
      imagePullSecrets:
        - name: regcred
      volumes: {{ include "misskey.volumes" . | nindent 8 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 2
