apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "-5"
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
    spec:
      restartPolicy: Never
      initContainers: {{ include "misskey.initContainers" . | nindent 8 }}
      containers:
        - name: "{{ .Release.Name }}"
          image: "{{ .Values.image.index }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["pnpm", "run", "init"]
          env:
            - name: NODE_ENV
              value: {{ .Values.environment }}
          volumeMounts:
            - name: {{ include "misskey.name" . }}-configuration-destination
              mountPath: /misskey/.config
        - name: "{{ .Release.Name }}-redis-init-job"
          image: public.ecr.aws/docker/library/redis:7.2.4-alpine
          command: ["/usr/local/bin/redis-cli"]
          args: ["-h", "{{ .Values.redis.host }}",{{ if .Values.redis.port }} "-p", "{{ .Values.redis.port }}",{{ end }} "CONFIG", "SET", "maxmemory-policy", "noeviction"]
      volumes: {{ include "misskey.volumes" . | nindent 8 }}
