apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}"
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "-5"
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
    spec:
      restartPolicy: Never
      initContainers: {{ include "misskey.initContainers" . | nindent 8 }}
      containers:
        - name: "{{ .Release.Name }}"
          image: "{{ .Values.image.index }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["pnpm", "run", "migrate"]
          env:
            - name: NODE_ENV
              value: {{ .Values.environment }}
          volumeMounts:
            - name: {{ include "misskey.name" . }}-configuration-destination
              mountPath: /misskey/.config
      volumes: {{ include "misskey.volumes" . | nindent 8 }}
