apiVersion: v1
kind: Service
metadata:
  name: {{ include "misskey.name" . }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      protocol: TCP
      name: http
  selector:
    app: {{ include "misskey.name" . }}
