apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hariko.name" . }}-pvc
  labels:
    app: {{ include "hariko.name" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
