image:
  pullPolicy: IfNotPresent
host: misskey.flowers
port: 3000
environment: production
postgresql:
  host: production-misskey-postgresql-rw.production-misskey-postgresql.svc.cluster.local
  port: 5432
  username: honi
  password: honi
  db: hm1
redis:
  host: production-misskey-dragonflydb.production-misskey-dragonflydb.svc.cluster.local
  port: 6379
  password: honi
redisForTimelines:
  host: production-misskey-dragonflydb-timeline.production-misskey-dragonflydb.svc.cluster.local
  port: 6379
  password: honi
migration:
  bskHost: misskey.backspace.fm
  bskSystemWebhookSecret: hoge

proxy: http://127.0.0.1:3128

meilisearch:
  scope: global

hanamisearch:
  scope: global

misskey:
  id: aidx
  proxyBypassHosts:
    - challenges.cloudflare.com
  proxyRemoteFiles: true
  signToActivityPubGet: true
  deliverJobPerSec: 512
  inboxJobPerSec: 512
  relationshipJobPerSec: 512
  clusterLimit: 3
  fulltextSearch:
    provider: sqlLike

sentryForBackend:
  enableNodeProfiling: true
