image:
  pullPolicy: IfNotPresent
host: misskey.flowers
port: 3000
environment: production
postgresql:
  host: production-misskey-pg-rw.default.svc.cluster.local
  port: 5432
  username:
    valueFrom:
      secretKeyRef:
        name: postgres-production-user-secret
        key: username
  password:
    valueFrom:
      secretKeyRef:
        name: postgres-production-user-secret
        key: password
  db: hm1
redis:
  host: dragonfly-misskey.default.svc.cluster.local
  port: 6379
  password:
    valueFrom:
      secretKeyRef:
        name: dragonfly-auth
        key: password
migration:
  bskHost: misskey.backspace.fm
  bskSystemWebhookSecret: hoge
misskey:
  id: aidx
  proxyBypassHosts:
    - challenges.cloudflare.com
  proxyRemoteFiles: false
  signToActivityPubGet: true
  deliverJobPerSec: 192
  inboxJobPerSec: 128
  relationshipJobPerSec: 128
