apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}"
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "-5"
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
    spec:
      restartPolicy: Never
      initContainers:
        - name: "{{ .Release.Name }}-init"
          image: mikefarah/yq:4
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args: ["-c", "cp /mnt/misskey-configuration/default.yml /misskey/.config && /usr/bin/yq -i \".db.pass = \\\"$POSTGRESQL_PASS\\\"\" /misskey/.config/default.yml"]
          env:
            - name: POSTGRESQL_PASS
              valueFrom:
                secretKeyRef:
                  name: postgresql-ha-postgresql
                  key: password
          volumeMounts:
            - name: {{ include "misskey.name" . }}-configuration-destination
              mountPath: /misskey/.config
            - name: {{ include "misskey.name" . }}-configuration
              mountPath: /mnt/misskey-configuration
              readOnly: true
      containers:
        - name: "{{ .Release.Name }}"
          image: "{{ .Values.image.index }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["pnpm", "run", "migrate"]
          env:
            - name: NODE_ENV
              value: {{ .Values.environment }}
          volumeMounts:
            - name: {{ include "misskey.name" . }}-configuration-destination
              mountPath: /misskey/.config
      volumes:
        - name: {{ include "misskey.name" . }}-configuration-destination
          emptyDir: {}
        - name: {{ include "misskey.name" . }}-configuration
          configMap:
            name: {{ include "misskey.name" . }}-configuration
