name: Build

on:
  push:
    branches:
    - master
    paths-ignore:
    - '.github/**'
    - '.editorconfig'
    - '.gitignore'
    - '**/*.md'
  workflow_dispatch:
    inputs:
      head:
        default: develop

jobs:
  update:
    if: github.repository == 'misskey-dev/0key.dev' && github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.6
      with:
        fetch-depth: 0
        fetch-tags: true
        submodules: recursive
    - run: |
        git branch -r --format '%(refname:short)' | while read r;
          do git branch --track "${r#origin/}" "$r" || :;
        done
        git fetch --all || :
        git pull --all --ff-only || :
        git checkout "$HEAD"
      env:
        HEAD: ${{ github.event.inputs.head }}
      working-directory: misskey
    - run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git add misskey
        git commit -m "chore: update misskey to $(git rev-parse HEAD)"
        git push
      env:
        HEAD: ${{ github.event.inputs.head }}
  docker-hariko:
    if: github.repository == 'misskey-dev/0key.dev'
    runs-on: ubuntu-latest
    permissions:
      packages: write
    outputs:
      digest: ${{ steps.build.outputs.digest }}
    steps:
    - uses: actions/checkout@v4.1.6
    - uses: docker/login-action@v3.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: crazy-max/ghaction-github-runtime@v3.0.0
    - id: build
      run: |
        docker build--cache-from type=gha,scope=hariko --cache-to type=gha,scope=hariko,mode=max -t "ghcr.io/misskey-dev/0key.dev:$GITHUB_REF_NAME-hariko" .
        docker push "ghcr.io/misskey-dev/0key.dev:$GITHUB_REF_NAME-hariko"
        echo "digest=$(docker image ls --format '{{.Digest}}' | head -n1)" > $GITHUB_OUTPUT
      working-directory: hariko
      env:
        GITHUB_REF_NAME: ${{ github.ref_name }}
  docker-misskey:
    if: github.repository == 'misskey-dev/0key.dev'
    runs-on: ubuntu-latest
    permissions:
      packages: write
    outputs:
      digest: ${{ steps.build.outputs.digest }}
    steps:
    - uses: actions/checkout@v4.1.6
      with:
        submodules: true
    - uses: docker/login-action@v3.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: Homebrew/actions/setup-homebrew@master
    - uses: crazy-max/ghaction-github-runtime@v3.0.0
    - id: build
      run: |
        head=$(git rev-parse HEAD)
        repository=$(mktemp -d)
        cd $repository
        git init
        git remote add origin https://github.com/misskey-dev/misskey.git
        git fetch --depth=1 origin $head
        git checkout FETCH_HEAD
        brew install jaq
        jaq --in-place ".version += \"-$(git rev-parse --abbrev-ref HEAD).$(git rev-parse HEAD)\"" package.json
        docker build --cache-from type=gha,scope=misskey --cache-to type=gha,scope=misskey,mode=max -t "ghcr.io/misskey-dev/0key.dev:$GITHUB_REF_NAME-misskey" .
        docker push "ghcr.io/misskey-dev/0key.dev:$GITHUB_REF_NAME-misskey"
        echo "digest=$(docker image ls --format '{{.Digest}}' | head -n1)" > $GITHUB_OUTPUT
      working-directory: misskey
      env:
        GITHUB_REF_NAME: ${{ github.ref_name }}
  helm:
    if: github.repository == 'misskey-dev/0key.dev'
    needs:
    - docker-hariko
    - docker-misskey
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4.1.6
      with:
        fetch-depth: 0
    - id: version
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        echo revision=$(git log --oneline | wc -l) > $GITHUB_OUTPUT
    - uses: azure/setup-helm@v4.2.0
      with:
        version: v3.15.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: mikefarah/yq@v4.44.1
      with:
        cmd: |
          yq -i ".version += \\"${{ steps.version.outputs.revision }}\\"" charts/hariko/Chart.yaml
          yq -i ".version += \\"${{ steps.version.outputs.revision }}\\"" charts/misskey/Chart.yaml
          yq -i ".image.index = \\"ghcr.io/misskey-dev/0key.dev@${{ needs.docker-hariko.outputs.digest }}\\"" charts/hariko/values.yaml
          yq -i ".image.index = \\"ghcr.io/misskey-dev/0key.dev@${{ needs.docker-misskey.outputs.digest }}\\"" charts/misskey/values.yaml
      env:
        GITHUB_REF_NAME: ${{ github.ref_name }}
    - uses: helm/chart-releaser-action@v1.6.0
      env:
        CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
