name: Build

on:
  push:
    branches:
    - master

jobs:
  docker-hariko:
    if: github.repository == 'misskey-dev/0key.dev'
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v4.1.6
    - uses: docker/login-action@v3.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        docker build -t "ghcr.io/misskey-dev/0key.dev:$GITHUB_REF_NAME-hariko" .
        docker push "ghcr.io/misskey-dev/0key.dev:$GITHUB_REF_NAME-hariko"
      working-directory: hariko
      env:
        GITHUB_REF_NAME: ${{ github.ref_name }}
  docker-misskey:
    if: github.repository == 'misskey-dev/0key.dev'
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v4.1.6
      with:
        submodules: true
    - uses: docker/login-action@v3.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: Homebrew/actions/setup-homebrew@master
    - run: |
        head=$(git rev-parse HEAD)
        repository=$(mktemp -d)
        cd $repository
        git init
        git remote add origin https://github.com/misskey-dev/misskey.git
        git fetch --depth=1 origin $head
        git checkout FETCH_HEAD
        brew install jaq
        jaq --in-place ".version += \"-$(git rev-parse --abbrev-ref HEAD).$(git rev-parse HEAD)\"" package.json
        docker build -t "ghcr.io/misskey-dev/0key.dev:$GITHUB_REF_NAME-misskey" .
        docker push "ghcr.io/misskey-dev/0key.dev:$GITHUB_REF_NAME-misskey"
      working-directory: misskey
      env:
        GITHUB_REF_NAME: ${{ github.ref_name }}
  helm:
    if: github.repository == 'misskey-dev/0key.dev'
    needs:
    - docker-hariko
    - docker-misskey
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4.1.6
      with:
        fetch-depth: 2
    - run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
    - uses: azure/setup-helm@v4.2.0
      with:
        version: v3.15.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: mikefarah/yq@v4.44.1
      with:
        cmd: |
          yq -i ".image.index = \\"ghcr.io/misskey-dev/0key.dev:$GITHUB_REF_NAME-hariko\\"" charts/helm/values.yaml
          yq -i ".image.index = \\"ghcr.io/misskey-dev/0key.dev:$GITHUB_REF_NAME-misskey\\"" charts/misskey/values.yaml
      env:
        GITHUB_REF_NAME: ${{ github.ref_name }}
    - uses: helm/chart-releaser-action@v1.6.0
      env:
        CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
