name: Update Misskey

on:
  workflow_dispatch:
    inputs:
      head:
        default: develop

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.6
      with:
        depth: 0
        submodules: recursive
    - run: |
        git branch -r --format '%(refname:short)' | while read r;
          do git branch --track "${r#origin/}" "$r";
        done
        git fetch --all
        git pull --all
        git checkout "$HEAD"
      env:
        HEAD: ${{ github.event.inputs.head }}
      working-directory: misskey
    - run: |
        git config --global user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git add misskey
        git commit -m "chore: update misskey to $HEAD"
        git push
      env:
        HEAD: ${{ github.event.inputs.head }}
